config/routes.rb
Rails.application.routes.draw do
  # routes
  # HTTP VERBS: get, post,, put, patch, delete

  # verb 'url/path' => 'controller#action' 

  #SHOW Routes
  get 'titles'     => 'titles#index' # Title Index (Show All Titles)
  get 'titles/:id' => 'titles#show', as: 'title', id: /\d+/ # Title Show (Show A Title)

  #CREATE Routes
  get 'titles/new' => 'titles#new', as: 'new_title'
  post 'titles' => 'titles#create'

  #UPDATE Routes
  get 'titles/:id/edit' => 'titles#edit', as: 'edit_title', id: /\d+/
  patch 'titles/:id' => 'titles#update'

  #DELETE Routes
  delete 'titles/:id' => 'titles#destroy'

  root to: 'titles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/title.rb
class Title < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
    @titles = Title.order(:name) # Load all titles ordered by name.
  end
  # Automatically load the app/views/titles/index.html.erb

  def show
    @title = find_title
  end
  # Automatically load the app/views/titles/show.html.erb

  def new
    @title = Title.new
  end
  # Automatically load the app/views/titles/new.html.erb

  def create
    @title = Title.new(title_params)

    if @title.save # If the validation pass
      redirect_to @title # Redirect to show action for this title
    else # If the validation fail
      render :new #Render the view associated with the new action.
    end
  end
  # This action does not have an associated view!

  def edit
    @title = find_title
  end
  # Automatically load the app/views/titles/edit.html.erb

  def update
    @title = find_title

    if @title.update(title_params) # If the validation pass
      redirect_to @title # Redirect to the show action for this title.
    else # If the validation fail
      render :edit # Render the edit view to show the form again and display validation errors.
    end
  end
  # No view associated with this action we either redirector render.

  def destroy
    @title = find_title
    @title.destroy

    redirect_to titles_url # Redirects to the titles index page.
  end

  private

  def find_title
    Title.find(params[:id]) # Load title mentioned by id in the route.
  end

  def title_params
    params.require(:title).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalYearProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <h1>Title Records Application</h1>
</header>

app/views/titles/_form.html.erb
<%= form_for(@title) do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>
      <ul>
      <% @title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
      </ul>
    </div>
  <% end %>
  <div>
  <%= f.label :name %>
  </div>
  <div>  
  <%= f.text_field :name %>
  </div>
<%= f.submit %>
<% end %>

app/views/titles/_title.html.erb
<!--

The name of the partial should match the model, with a prepended underscore.
The name of the variable we use within the partial should match the partial name.

-->

  <div class='title'>
    <p>
      <strong>Name:</strong> <%= link_to title.name, title_path(title) %>
      - <%= link_to 'edit', edit_title_path(title) %>
      - <%= link_to 'delete', title_path(title), method: :delete, data: { confirm: 'Are you sure you want to delete this title?'} %>
    </p>
  </div>

app/views/titles/edit.html.erb
<h2>Edit Title</h2>

<%= render partial: 'form' %>

app/views/titles/index.html.erb
<h2>All Titles</h2>

<%= render partial: 'title', collection: @titles %>

<p>
  <%= link_to 'Create New Title', new_title_path %>
</p>

app/views/titles/new.html.erb
<h2>Create a New Title</h2>

<%= form_for(@title) do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>
      <ul>
      <% @title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
      </ul>
    </div>
  <% end %>
  <div>
  <%= f.label :name %>
  </div>
  <div>  
  <%= f.text_field :name %>
  </div>
<%= f.submit %>
<% end %>

app/views/titles/show.html.erb
<h2>Title Information</h2>

<%= render partial: 'title', object: @title %>

<p><%= link_to 'Back to All Titles', titles_path %></p>